name: 'PmmpUnit Tests'
description: 'Run PmmpUnit Tests'

inputs:
  suite-test:
    description: "Suite test to run"
    required: true
  tests-path:
    description: 'Path to tests'
    required: true
    default: 'tests/pmmpunit'
  php-version:
    description: 'PHP version'
    required: true
    default: '8.1'
  env-file:
    description: 'Path to env file'
    required: false
    default: '.env'
  timeout:
    description: 'Timeout for tests (in seconds)'
    required: false
    default: '60'
  mysql:
    description: 'If mysql needs to be started'
    required: true
    default: 'false'
  mysql-version:
    description: 'Mysql version'
    required: false
    default: '8.0'
  mysql-entrypoint:
    description: 'Mysql entrypoint script (folder/file)'
    required: false
    default: ''

outputs:
  failed-tests:
    description: 'Number of failed tests'

runs:
  using: 'composite'
  steps:
    - name: 'Prepare environment'
      shell: bash
      id: "prepare"
      run: "${{github.action_path}}prepare.sh ${{ inputs.php-version }} ${{ inputs.tests-path }} ${{ inputs.suite-test }} ${{ inputs.env-file }} ${{ inputs.mysql }} ${{ inputs.mysql-version }} ${{ inputs.mysql-entrypoint }}"

    - name: 'Run tests'
      shell: bash
      id: "run"
      run: "${{github.action_path}}run.sh ${{ steps.prepare.outputs.pocketmine_name }} ${{ inputs.timeout }} ${{ steps.prepare.outputs.mysql_name }}"

    - name: 'Collect results'
      shell: bash
      id: "finish"
      run: "${{github.action_path}}exitpoint.sh ${{ steps.prepare.outputs.pocketmine_name }}"

  post:
    - name: "Cleanup"
      shell: bash
      run: "${{github.action_path}}cleanup.sh ${{ steps.prepare.outputs.container_prefix }}